services:
  - type: web
    name: hse-maestranza-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: ALLOW_PUBLIC_REGISTER
        value: "false"
      - key: AUTO_SYNC_DB
        value: "true"
      - key: CORS_ORIGIN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
